
name: CI

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run application
        run: python main.py

  post-ci:
    runs-on: ubuntu-latest
    needs: ci
    if: always()

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Write result
        run: |
          mkdir -p .github

          if [ "${{ needs.ci.result }}" = "success" ]; then
            echo "Ok" > .github/ci-results.txt
          else
            echo "Fallito" > .github/ci-results.txt
          fi

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .github/ci-results.txt

          if ! git diff --cached --quiet; then
            git commit -m "Update CI results"
          fi

      - name: Push changes
        run: |
          BRANCH="${{ github.event.repository.default_branch }}"
          git push origin HEAD:$BRANCH
